# camera parameters
video_device: "/dev/video0" # change this to your video device path
image_width: 1280
image_height: 720
pixel_format: yuyv
camera_frame_id: "usb_cam"
io_method: "mmap"
framerate: 5